name: Run Tweet Bot

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Stops the job if it runs longer than 8 minutes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write Google Credentials File
        run: |
          cat <<EOF > credentials.json
          ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          EOF

      - name: Verify credentials.json
        run: cat credentials.json

      - name: Run tweet bot and capture output
        id: run_bot
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SERVICE_ACCOUNT_FILE: credentials.json
        run: |
          python GLRECS-BOT/GLRECS.py 2>&1 | tee bot_output.log
          echo "Bot execution completed."

      - name: Print bot output
        run: cat bot_output.log

      - name: List files in directory
        run: ls -la

      - name: Upload bot output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot_output.log
          path: bot_output.log
